# -*- coding: utf-8 -*-
"""Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQiFA4Bpxi2r__be389znB5Vi_SG2kXW
"""

a=float(input("Enter the price of item 1: "))
b=float(input("Enter the price of item 2: "))
c=float(input("Enter the price of item 3: "))
sum=a+b+c
if sum>50:
  new_sum = 0.9*sum
  print("Total price with discount = ",new_sum)
else:
  print("Total price with discount = ",sum)

