# -*- coding: utf-8 -*-
"""Case Study 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M8V3nKH2RoDaBhdQtifuMp6tK4cn-njm
"""

import random

num = random.randint(1,100)

count=1
flag=0
while count<=7:
  guess=int(input("Guess a number between 1 and 100: "))
  if guess>num:
    if count!=7:
      print("Too High! Try again.")
    count+=1
  elif guess<num:
    if count!=7:
      print("Too Low! Try again.")
    count+=1
  else:
    if count==1:
      print(f"Congratulations! You guessed the number in {count} attempt.")
      flag=1
      break
    else:
      print(f"Congratulations! You guessed the number in {count} attempts.")
      flag=1
      break

if flag==0:
  print(f"Game Over! The number was {num}.")

